{% set version = "1.1.13" %}

package:
  name: nss_wrapper
  version: {{ version }}

source:
  url: https://ftp.samba.org/pub/cwrap/nss_wrapper-{{ version }}.tar.gz
  sha256: 449844cb5e4f3e250ac9656ab314ea6e576ba3fe9f0897a065e0e3e427ef8cd8

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make

test:
  commands:
    - test -f $PREFIX/lib/libnss_wrapper.so

about:
  home: https://cwrap.org/nss_wrapper.html
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A wrapper for the user, group and hosts NSS API
  description: |
    There are projects that need to be able to create, modify, and delete Unix
    users. Others just switch user IDs to interact with the system on behalf
    of another user (e.g. a user space file server). To be able to test
    applications like these, you need to grant privileges to modify the passwd
    and group files. With nss_wrapper it is possible to define your own passwd
    and group files to be used the software while it is under test. The
    nss_wrapper also allows you to create a hosts file to set up name
    resolution for the addresses you use with socket_wrapper.

extra:
  recipe-maintainers:
    - chrisburr
